providers = ["node"]

[phases.install]
cmds = ["cd website && npm ci", "cd server && npm ci --production"]

[phases.build]
cmds = ["cd website && npm run build"]

[start]
cmd = "node server/index.js"
